version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7.1-cli-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - dependencies-{{ checksum "composer.json" }}
          - dependencies-
      - run: composer install -n --prefer-dist
      - save_cache:
          paths:
            - ./vendor
          key: dependencies-{{ checksum "composer.json" }}
      - run: composer run cs-check
      - run: composer run test